const API_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3ZTYzYTYzMC00NzYwLTRiZjEtOTViOC0zNTBjMTQxZDZkZjkiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwianRpIjoiZDJjMDgxODUtNDA3YS00NzVhLWJjZjMtMDM4ZmI1ZWEyMjAyIiwiaWF0IjoxNzc4MTQ3NTk3fQ.IbGlhTHCcVL5nM9wF3SbnmxgGhRnIsino1m0l3HdXSY';
const BASE = 'http://localhost:5678/api/v1';
const H = { 'Content-Type': 'application/json', 'X-N8N-API-KEY': API_KEY };

// Fix: Build Markdown Output reads from Call Writer Service, not Save Draft Version
const buildMdCode = [
  'var writerResp = $("Call Writer Service").first().json;',
  'var chData = writerResp.data || writerResp;',
  'var proj = $("Load Active Project").first().json;',
  'var plan = $("Select Next Chapter Plan").first().json;',
  '',
  'var title = chData.title || plan.title || "Untitled";',
  'var content = chData.body_markdown || chData.content || "";',
  'var wordCount = chData.word_count || content.length;',
  'var summary = chData.summary || "";',
  'var date = new Date().toISOString().split("T")[0];',
  'var seq = plan.sequence || 1;',
  '',
  'var md = "# " + title + "\\n\\n";',
  'md += "> 项目: " + (proj.name || "") + " | 章节: " + seq + " | 日期: " + date + " | 字数: " + wordCount + "\\n\\n";',
  'if (summary) md += "> " + summary + "\\n\\n";',
  'md += content + "\\n\\n";',
  'md += "---\\n";',
  'md += "*Generated by AI Novel Factory*\\n";',
  '',
  'var slug = (proj.name || "novel").replace(/[^a-zA-Z0-9\\u4e00-\\u9fff]+/g, "-").toLowerCase();',
  'var filename = "/data/paper/" + slug + "-ch" + String(seq).padStart(3,"0") + ".md";',
  '',
  'return [{ json: { filename: filename, content: md, title: title, sequence: seq, word_count: wordCount } }];'
].join('\n');

async function main() {
  const resp = await fetch(BASE + '/workflows/hCkthWAH1GxEvLYU', { headers: H });
  const wf = await resp.json();

  const bmo = wf.nodes.find(n => n.name === 'Build Markdown Output');
  if (bmo) {
    bmo.parameters.jsCode = buildMdCode;
    console.log('Fixed Build Markdown Output - reads from Call Writer Service');
  }

  wf.settings = { executionOrder: 'v1' };
  const r = await fetch(BASE + '/workflows/' + wf.id, {
    method: 'PUT', headers: H,
    body: JSON.stringify({ name: wf.name, nodes: wf.nodes, connections: wf.connections, settings: wf.settings })
  });
  console.log(r.ok ? 'Updated! Run WF03' : 'FAIL');
}
main().catch(e => console.error(e));
