const API_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3ZTYzYTYzMC00NzYwLTRiZjEtOTViOC0zNTBjMTQxZDZkZjkiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwianRpIjoiZDJjMDgxODUtNDA3YS00NzVhLWJjZjMtMDM4ZmI1ZWEyMjAyIiwiaWF0IjoxNzc4MTQ3NTk3fQ.IbGlhTHCcVL5nM9wF3SbnmxgGhRnIsino1m0l3HdXSY';
const BASE = 'http://localhost:5678/api/v1';
const H = { 'Content-Type': 'application/json', 'X-N8N-API-KEY': API_KEY };

const smartParse = [
  'var response = $input.first().json;',
  'var rawText = "";',
  'if (response["message"] && response["message"]["content"]) rawText = response["message"]["content"];',
  'else if (response["choices"] && response["choices"][0]) rawText = response["choices"][0]["message"]["content"];',
  'else if (typeof response === "string") rawText = response;',
  'else rawText = JSON.stringify(response);',
  '',
  'rawText = rawText.trim();',
  'if (rawText.startsWith("```")) { var nl = rawText.indexOf("\\n"); if (nl >= 0) rawText = rawText.substring(nl + 1); }',
  'if (rawText.endsWith("```")) rawText = rawText.substring(0, rawText.length - 3).trim();',
  '',
  'var plan;',
  'try { plan = JSON.parse(rawText); }',
  'catch (e) { throw new Error("JSON parse failed: " + e.message + ". Raw: " + rawText.substring(0, 300)); }',
  '',
  '// Smart extraction: find chapters array anywhere in the plan',
  'function findChapters(obj, depth) {',
  '  if (!obj || typeof obj !== "object" || depth > 5) return [];',
  '  // Direct array of objects with title',
  '  if (Array.isArray(obj) && obj.length > 0 && obj[0]["title"]) return obj;',
  '  // Search in object values',
  '  if (!Array.isArray(obj)) {',
  '    var keys = Object.keys(obj);',
  '    // Try known key names first',
  '    for (var i = 0; i < keys.length; i++) {',
  '      var k = keys[i];',
  '      var v = obj[k];',
  '      if (Array.isArray(v) && v.length > 0 && v[0]["title"]) return v;',
  '    }',
  '    // Recurse into objects',
  '    for (var i = 0; i < keys.length; i++) {',
  '      var v = obj[keys[i]];',
  '      if (typeof v === "object" && v !== null && !Array.isArray(v)) {',
  '        var found = findChapters(v, depth + 1);',
  '        if (found.length > 0) return found;',
  '      }',
  '    }',
  '  }',
  '  return [];',
  '}',
  '',
  'function findArrays(obj) {',
  '  var result = { chapters: [], plotThreads: [], foreshadowing: [] };',
  '  if (!obj || typeof obj !== "object") return result;',
  '  if (Array.isArray(obj)) return result;',
  '  ',
  '  // Find chapters',
  '  result.chapters = findChapters(obj, 0);',
  '  ',
  '  // Find any array that looks like plot threads (has "name" or "status")',
  '  var keys = Object.keys(obj);',
  '  for (var i = 0; i < keys.length; i++) {',
  '    var v = obj[keys[i]];',
  '    if (Array.isArray(v) && v.length > 0 && (v[0]["name"] || v[0]["status"]) && !v[0]["title"]) {',
  '      if (!result.plotThreads.length) result.plotThreads = v;',
  '      else if (!result.foreshadowing.length) result.foreshadowing = v;',
  '    }',
  '  }',
  '  ',
  '  // Also search in nested objects',
  '  for (var i = 0; i < keys.length; i++) {',
  '    var v = obj[keys[i]];',
  '    if (typeof v === "object" && v !== null && !Array.isArray(v)) {',
  '      var nested = findArrays(v);',
  '      if (nested.chapters.length > 0 && result.chapters.length === 0) result.chapters = nested.chapters;',
  '      if (nested.plotThreads.length > 0 && result.plotThreads.length === 0) result.plotThreads = nested.plotThreads;',
  '      if (nested.foreshadowing.length > 0 && result.foreshadowing.length === 0) result.foreshadowing = nested.foreshadowing;',
  '    }',
  '  }',
  '  ',
  '  return result;',
  '}',
  '',
  'var extracted = findArrays(plan);',
  '',
  '// Get summary text - try multiple possible keys recursively',
  'function findString(obj, keys) {',
  '  if (!obj || typeof obj !== "object") return "";',
  '  if (Array.isArray(obj)) return "";',
  '  for (var i = 0; i < keys.length; i++) {',
  '    if (typeof obj[keys[i]] === "string") return obj[keys[i]];',
  '  }',
  '  // Search nested',
  '  var objKeys = Object.keys(obj);',
  '  for (var i = 0; i < objKeys.length; i++) {',
  '    var v = obj[objKeys[i]];',
  '    if (typeof v === "object" && v !== null && !Array.isArray(v)) {',
  '      var found = findString(v, keys);',
  '      if (found) return found;',
  '    }',
  '  }',
  '  return "";',
  '}',
  '',
  'var summary = findString(plan, ["weekly_summary", "plan_summary", "plan_description", "summary", "description", "plan_name"]);',
  '',
  'var proj = $("Load Active Project").first().json;',
  '',
  'return [{ json: {',
  '  project_id: proj["id"],',
  '  plan: plan,',
  '  chapters: extracted.chapters,',
  '  plot_threads: extracted.plotThreads,',
  '  foreshadowing: extracted.foreshadowing,',
  '  weekly_summary: summary,',
  '  next_sequence_start: ($("Build Planning Context").first().json["next_sequence_start"] || 1)',
  '}}];'
].join('\n');

const smartBuildSQL = [
  'var data = $input.first().json;',
  'var pid = data.project_id;',
  '// Use pre-extracted chapters array, or fall back to searching plan',
  'var chapters = data.chapters || [];',
  'if (chapters.length === 0) {',
  '  var plan = data.plan;',
  '  // Try flat keys',
  '  chapters = plan["chapter_plans"] || plan["chapters_plan"] || plan["chapters"] || [];',
  '  // Try nested weekly_plan',
  '  if (chapters.length === 0 && plan["weekly_plan"]) {',
  '    chapters = plan["weekly_plan"]["chapters"] || [];',
  '  }',
  '}',
  '',
  'function esc(val) {',
  '  if (val === undefined || val === null) return "NULL";',
  '  if (typeof val === "boolean") return val ? "TRUE" : "FALSE";',
  '  if (typeof val === "number") return String(val);',
  '  var str = typeof val === "object" ? JSON.stringify(val) : String(val);',
  '  return "\x27" + str.replace(/\x27/g, "\x27\x27") + "\x27";',
  '}',
  '',
  'var items = [];',
  'for (var i = 0; i < chapters.length; i++) {',
  '  var cp = chapters[i];',
  '  var seq = cp["sequence"] || cp["chapter_number"] || i + 1;',
  '  items.push({ json: { sql: "INSERT INTO chapter_plans (project_id, sequence, title, plot_goals, outline, target_word_count, status) VALUES ("',
  '    + esc(pid) + ", " + esc(seq) + ", "',
  '    + esc(cp["title"] || ("Chapter " + seq)) + ", "',
  '    + esc(cp["plot_goals"] || cp["goals"] || []) + ", "',
  '    + esc(cp["summary"] || cp["expected_conflict"] || cp["description"] || "") + ", "',
  '    + esc(cp["target_word_count"] || cp["word_count"] || 3000) + ", "',
  '    + esc("planned") + ") RETURNING id"',
  '  }});',
  '}',
  'if (items.length === 0) items.push({ json: { sql: "SELECT 1 AS note" } });',
  'return items;'
].join('\n');

const smartSummary = [
  'var data = $("Parse Arc Plan").first().json;',
  'var chapters = data["chapters"] || [];',
  'var pt = data["plot_threads"] || [];',
  'var fs = data["foreshadowing"] || [];',
  'var summary = data["weekly_summary"] || "";',
  '',
  'return [{ json: {',
  '  project_id: data["project_id"],',
  '  chapters_planned: chapters.length,',
  '  plot_threads_updated: pt.length,',
  '  foreshadowing_updated: fs.length,',
  '  human_review_count: 0,',
  '  human_review_items: [],',
  '  weekly_summary: summary,',
  '  pacing_analysis: "",',
  '  status: "weekly_plan_complete"',
  '}}];'
].join('\n');

async function main() {
  const resp = await fetch(BASE + '/workflows/RGbsc6NtL3uHqKSk', { headers: H });
  const wf = await resp.json();

  let fixed = 0;
  const updates = [
    ['Parse Arc Plan', smartParse],
    ['Build Plan SQLs', smartBuildSQL],
    ['Weekly Plan Summary', smartSummary]
  ];
  for (const [name, code] of updates) {
    const node = wf.nodes.find(n => n.name === name);
    if (node) { node.parameters.jsCode = code; fixed++; console.log('Fixed:', name); }
  }

  if (wf.settings) { for (const k of Object.keys(wf.settings)) { if (wf.settings[k] === null) delete wf.settings[k]; } }

  const r = await fetch(BASE + '/workflows/' + wf.id, {
    method: 'PUT', headers: H,
    body: JSON.stringify({ name: wf.name, nodes: wf.nodes, connections: wf.connections, settings: { executionOrder: 'v1' } })
  });
  console.log(r.ok ? 'Updated! (' + fixed + ' nodes) Run WF05' : 'FAIL');
}
main().catch(e => console.error(e));
